apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solra-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fisa4th-final-project/solra.git'
    targetRevision: dev
    path: deploy/app/monitoring
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: solra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
