apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solra-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fisa4th-final-project/solra.git'
    targetRevision: dev
    path: deploy/app/monitoring/charts/kube-prometheus-stack
    helm:
      valueFiles:
        - ../../values.yaml
      skipCrds: true     # ✅ CRD 생략 설정
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: solra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers: []