grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 32000

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 32001
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          storageClassName: ""


prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true