grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 32000

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 32001
  prometheusSpec:
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          storageClassName: local-path
          
    additionalScrapeConfigs:
      - job_name: 'mysql-backup-monitor'
        static_configs:
          - targets: ['10.5.100.42:9100']


prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true
