apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.15.5
    helm:
      values: |
        config:
          clients:
            - url: http://loki.solra-monitoring.svc.cluster.local:3100/loki/api/v1/push
          snippets:
            pipelineStages:
              - cri: {}
            scrapeConfigs: |
              - job_name: kubernetes-pods
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_label_app]
                    target_label: app
                  - source_labels: [__meta_kubernetes_namespace]
                    target_label: namespace
                  - source_labels: [__meta_kubernetes_pod_name]
                    target_label: pod
                  - source_labels: [__meta_kubernetes_pod_container_name]
                    target_label: container
                  - action: replace
                    source_labels: [__meta_kubernetes_pod_container_name]
                    target_label: __path__
                    replacement: /var/log/containers/*$1*.log
                  - action: keep
                    source_labels: [__meta_kubernetes_namespace]
                    regex: solra
        extraVolumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: containers
            hostPath:
              path: /var/log/containers
        extraVolumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: containers
            mountPath: /var/log/containers
            readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: solra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
