apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../app
  - ../../base

# patchesStrategicMerge:
#   - patch.yaml

commonAnnotations:
  sync-tag: "3044bd7bfd4465413082c482c8609b2cfbfa3f2b"