apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../app
  - ../../base

# patchesStrategicMerge:
#   - patch.yaml

commonAnnotations:
  sync-tag: "7c9936ef7c3c54ca3c4602ddccb459e552ce9dac"