apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../app
  - ../../base

# patchesStrategicMerge:
#   - patch.yaml

commonAnnotations:
  sync-tag: "9ddecdec08470d77c926e2c9ae887c537061cd16"