apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - solra-backend-app.yaml
  - solra-frontend-app.yaml
  - solra-redis-app.yaml
  - monitoring/solra-monitoring-app.yaml
  - ingress-nginx/ingress-ngnix-app.yaml
