apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-monkey
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://asobti.github.io/kube-monkey/charts/repo
    chart: kube-monkey
    targetRevision: 1.5.2
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: solra-kube-monkey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
