config:
  dryRun: true
  runHour: 16                   # 지금 바로 실행 가능
  startHour: 17                 # 실행 시작 시각 = 현재 시각
  endHour: 18                   # 실행 종료 시각
  timeZone: "Asia/Seoul"

  whitelistedNamespaces:
    - solra
    - solra-jenkins
    - solra-harbor

  blacklistedNamespaces:
    - kube-system
    - argocd
    - redis
    - solra-gitlab
    - solra-monitoring
    - solra-cert
    - solra-kube-monkey

  debug:
    enabled: true
    schedule_immediate_kill: true  # 즉시 실행!

  notifications:
    enabled: true
    proxy: ""
    attacks: |
      slack = true
      email = false

resources:
  limits:
    cpu: 100m
    memory: 128Mi