config:
  dryRun: true
  runHour: 4
  startHour: 4
  endHour: 5
  timeZone: "Asia/Seoul"

  whitelistedNamespaces:
    - solra
    - solra-jenkins
    - solra-harbor

  blacklistedNamespaces:
    - kube-system
    - argocd
    - redis
    - solra-gitlab
    - solra-monitoring
    - solra-cert
    - solra-kube-monkey

resources:
  limits:
    cpu: 100m
    memory: 128Mi
