config:
  dryRun: true
  runHour: 3                  # ✅ KST 16:00 (오후 4시)에 해당
  startHour: 3
  endHour: 4
  timeZone: "Asia/Seoul"

  whitelistedNamespaces:
    - solra
    - solra-jenkins
    - solra-harbor

  blacklistedNamespaces:
    - kube-system
    - argocd
    - redis
    - solra-gitlab
    - solra-monitoring
    - solra-cert
    - solra-kube-monkey

resources:
  limits:
    cpu: 100m
    memory: 128Mi
