apiVersion: v1
kind: Secret
metadata:
  name: dev-secret
type: Opaque
stringData:
  SPRING_DB_USERNAME: "dev-db-username"
  SPRING_DB_PASSWORD: "dev-db-password"
  SPRING_JWT_SECRET: "dev-jwt-secret"
  SPRING_JWT_EXPIRATION: "3600"
  VUE_API_URL: "https://api.example.com"

---

apiVersion: v1
kind: Secret
metadata:
  name: prod-secret
type: Opaque
stringData:
  DB_USERNAME: "prod-db-username"
  DB_PASSWORD: "prod-db-password"
  JWT_SECRET: "prod-jwt-secret"
  JWT_EXPIRATION: "3600"
  VUE_API_URL: "https://api.example.com"
