apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.45.0
    helm:
      values: |
        mode: monolithic

        loki:
          auth_enabled: false

          storage:
            type: filesystem

          storage_config:
            boltdb_shipper:
              active_index_directory: /var/loki/index
              cache_location: /var/loki/index_cache
              shared_store: filesystem
            filesystem:
              directory: /var/loki/chunks

          schema_config:
            configs:
              - from: 2024-01-01
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  prefix: index_
                  period: 24h

        persistence:
          enabled: true
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          size: 10Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: solra-monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
