apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.41.3
    helm:
      values: |
        loki:
          isDefault: true
          persistence:
            enabled: true
            size: 10Gi
            storageClassName: standard
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: solra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
