apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.9.11
    helm:
      values: |
        loki:
          enabled: true
          auth_enabled: false
          persistence:
            enabled: true
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            size: 10Gi

          service:
            type: NodePort
            port: 3100
            nodePort: 31090

        promtail:
          enabled: false

        grafana:
          enabled: false

        fluent-bit:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: solra-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
