apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solra-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/fisa4th-final-project/solra.git'
    targetRevision: dev
    path: deploy/overlays/dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
