[master]
master ansible_host=192.168.0.202 ansible_port=2215 ansible_user=ubuntu internal_ip=10.0.2.100

[worker]
worker01 ansible_host=192.168.0.202 ansible_port=2216 ansible_user=ubuntu internal_ip=10.0.2.110
worker02 ansible_host=192.168.0.202 ansible_port=2217 ansible_user=ubuntu internal_ip=10.0.2.120

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
