apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solra-ingress
  namespace: solra
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: solra.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: solra-backend
                port:
                  number: 8080

          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: solra-frontend
                port:
                  number: 80
